server {
    # O Nginx vai escutar na porta 80 dentro do contêiner.
    listen 80;
    server_name localhost;

    # Todas as requisições que chegarem serão tratadas aqui.
    location / {
        # Repassa a requisição para o serviço 'app_dotnet' na porta 8000.
        # O Docker vai traduzir 'app_dotnet' para o IP interno correto.
        proxy_pass http://app_dotnet:8000;

        # Cabeçalhos padrão para garantir a comunicação correta com a aplicação .NET.
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
   }
}


